RAW_ALLOWED = {
    "help",
    "list",
    "see",
    "pos",
    "windows",
    "click",
    "double",
    "right",
    "move",
    "drag",
    "type",
    "key",
    "hotkey",
    "scroll",
    "screenshot",
    "read_chat",
    "chat_state",
    "chat_new",
    "read_frames",
    "read_scroll",
    "reply_new",
    "browser_youtube",
    "browser_google",
    "browser_chatgpt",
    "browser_open",
    "browser_search_google",
    "browser_search_youtube",
    "self_test",
    "auto_configure",
    "quit",
    "exit",
}


def command_allowed(command, subcommand=None):
    allowed = {
        ("raw", None),
        ("batch", "run"),
        ("mouse", "click"),
        ("mouse", "move"),
        ("mouse", "scroll"),
        ("mouse", "pos"),
        ("text", "type"),
        ("text", "key"),
        ("text", "hotkey"),
        ("text", "copy"),
        ("text", "paste"),
        ("text", "undo"),
        ("text", "select-all"),
        ("text", "alt-tab"),
        ("chat", "send"),
        ("chat", "send-click"),
        ("chat", "read"),
        ("chat", "state"),
        ("chat", "new"),
        ("chat", "read-frames"),
        ("chat", "read-scroll"),
        ("chat", "reply-new"),
        ("window", "focus"),
        ("window", "list"),
        ("browser", "chatgpt"),
        ("browser", "youtube"),
        ("browser", "google"),
        ("browser", "open"),
        ("browser", "search-google"),
        ("browser", "search-youtube"),
        ("browser", "focus"),
        ("screen", "see"),
        ("screen", "shot"),
        ("compat", "self-test"),
        ("compat", "auto-configure"),
        ("session", "grant"),
        ("session", "revoke"),
        ("session", "status"),
    }
    return (command, subcommand) in allowed


def raw_command_allowed(line):
    parts = line.strip().split()
    if not parts:
        return True
    return parts[0].lower() in RAW_ALLOWED
